spring:
 data:
  mongodb:
   host:localhost
   database:student
   port:27017
   password:mypassword
   name:student
 devtools:
  restart:
    enabled:true
    poll-interval:2s
    quiet-period:1s